### ISSUE TITLE
UI overflows offscreen for ultrawide monitors

### ISSUE THREAD

**Issue by PhaZ90771** [7w1/Pixel-That-Web#1]
![UI-Overflowing-Offscreen](https://user-images.githubusercontent.com/1004105/127750274-f1669072-bcfc-41c0-8120-dae8494edcda.PNG)

**Comment by 7w1** [comment]
Fixed in work in progress version. UI now gets locked to a 16:9 aspect ratio. I might add more aspect ratios in the future.
