### ISSUE TITLE
can you make it where you can import a save from the beginning

### ISSUE THREAD

**Issue by hankypoo7** [7w1/Pixel-That-Web#4]
can you make it where you can import a save from the beginning because it takes 30 minutes of my time each time my Chromebook restarts to get there

**Comment by 7w1** [comment]
Sure. I'll push a small update once I re-learn how to use Godot.

**Comment by 7w1** [comment]
Okay, it's been added. The game link has changed, it can be played here: https://rawcdn.githack.com/7w1/Pixel-That-Web/53f5f26a7b6d9aab53e513213474478583515385/old/index.html

**Comment by hankypoo7** [comment]
@7w1 thank you so much 🙏🏼
